name: fluttergithub
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+1
  dio: ^3.0.9
  provider: 5.0.0
  #intl: ^0.15.3
  cached_network_image: ^2.2.0+1
  fluttertoast: ^8.0.8
  flukit: ^1.0.2
  common_utils: ^1.1.3
  flutter_markdown: ^0.5.0
  flutter_spinkit: "^4.1.2"
  webview_flutter: 2.0.0
  transparent_image: ^1.0.0
  event_bus: ^1.1.0
  sqflite: ^1.1.0
  url_launcher: 6.0.1
  photo_view:
    git:
      url: https://github.com/CarSmallGuo/photo_view.git
      ref: master


dev_dependencies:
  json_model:
    git:
      url: "https://github.com/wbtvc/json_model.git"
  build_runner: ^1.6.0
  json_serializable: ^3.0.0
  #intl_translation: 0.17.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - imgs/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: myIcon
      fonts:
        - asset: fonts/iconfont.ttf
    - family: fileIcon
      fonts:
        - asset: fonts/fileiconfont.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
